# Details of queries (dev)
logging:
  level:
    org:
      springframework:
        jdbc:
          core: TRACE
    sql: debug

spring:
  application:
    name: project-java-spring-boot
  profiles:
    active: dev
  messages:
    encoding: UTF-8

  datasource:
    url: jdbc:sqlserver://localhost:1433;databasename=ENCHERES_DB;integratedSecurity=false;encrypt=false;trustServerCertificate=false
    username: sa
    password: Pa$$w0rd
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver